---

- name: Check network device OS
  assert:
    that: >
      ansible_os_family == 'nxos' or
      ansible_os_family == 'ios'

- name: Enable features
  nxos_feature:
    feature: "{{ device_features }}"
    state: enabled
  when: >
    ansible_os_family == 'nxos'
  tags: 
    - enable_features