---

- name: Check network device OS
  assert:
    that: >
      ansible_network_os == 'nxos' or
      ansible_network_os == 'ios' 

- name: Enable features
  nxos_feature:
    feature: "{{ item }}"
    state: enabled
  with_items: "{{ device_features }}"
  when: >
    ansible_network_os == 'nxos'
  tags: 
    - enable_features