---

- name: Check network device OS
  assert:
    that: >
      ansible_network_os == 'nxos' or
      ansible_network_os == 'ios' 

- name: Enable features
  nxos_feature:
    feature: "{{ item.name }}"
    state: "{{ item.state | default(omit) }}"
  loop: "{{ device_features }}"
  when: >
    ansible_network_os == 'nxos' and
    device_features is defined
  tags: 
    - enable_features
    - nxos